

// Array of jokes
        const jokes = [
            "Why don’t programmers like nature? Too many bugs.",
  "I told my computer I needed a break, and it froze.",
  "Why do Java developers wear glasses? Because they don’t C#.",
  "Debugging is like being a detective in a crime movie where you are also the murderer.",
  "Why was the computer cold? It forgot to close Windows.",
  "I changed my password to incorrect. Now it reminds me when I forget.",
  "Why did the programmer quit his job? He didn’t get arrays.",
  "Computers make very fast, very accurate mistakes.",
  "Why was the cell phone wearing glasses? It lost its contacts.",
  "There are 10 kinds of people: those who understand binary and those who don’t.",

  "Why did the laptop go to therapy? Too many crashes.",
  "I love pressing F5. It’s so refreshing.",
  "Why did the computer show up late? It had a hard drive.",
  "Why was the keyboard tired? Too many shifts.",
  "The cloud is just someone else’s computer.",
  "Why don’t robots panic? They have backups.",
  "My code works… I have no idea why.",
  "Why did the developer go broke? Used up all his cache.",
  "Real programmers count from 0.",
  "Why was the smartphone angry? Too many notifications.",

  "Why do programmers prefer dark mode? Light attracts bugs.",
  "I tried to learn recursion, but I tried to learn recursion.",
  "Why did the database break up? Too many relationships.",
  "Why was the computer sticky? Someone spilled syrup.exe.",
  "Why do programmers hate the outdoors? The sun causes glare.",
  "My computer sings sometimes. It’s Dell.",
  "Why was the monitor embarrassed? It saw too much screen time.",
  "I have a joke about UDP, but you might not get it.",
  "Why did the mouse feel important? It had a lot of clicks.",
  "Why did the code fail? It took things literally.",

  "Why was the programmer always calm? He had good exception handling.",
  "I named my hard drive ‘Data’. Now I lost Data.",
  "Why did the computer sneeze? It caught a virus.",
  "Why did the AI cross the road? That’s classified.",
  "Why did the server go broke? It lost its balance.",
  "Why don’t computers argue? They just process.",
  "Why was the byte scared? It saw a bit.",
  "Why do coders hate math? Too many problems.",
  "Why did the loop break up? It got stuck.",
  "Why was the file sad? It was deleted.",

  "Why do programmers like coffee? It helps them Java.",
  "Why was the printer angry? Paper jam again.",
  "Why was the password weak? It skipped leg day.",
  "Why did the app crash? Emotional overload.",
  "Why don’t computers gossip? Too much data.",
  "Why did the phone go to school? To get smarter.",
  "Why did the computer blush? It saw your browser history.",
  "Why was the algorithm confident? It had a solution.",
  "Why did the programmer bring a ladder? To reach high-level code.",
  "Why do bugs love code? Free housing.",

  "Why was the RAM jealous? The CPU got all the attention.",
  "Why did the website feel slow? Too many visitors.",
  "Why was the laptop stressed? Too many tabs open.",
  "Why did the function return early? It was tired.",
  "Why don’t programmers lie? The truth always comes out in logs.",
  "Why did the phone break up? No connection.",
  "Why was the code nervous? It was about to be executed.",
  "Why was the hard disk proud? It stored everything.",
  "Why did the variable feel empty? It was null.",
  "Why was the program optimistic? No errors yet.",

  "Why did the coder sleep at work? Infinite loop.",
  "Why was the bug confident? It survived testing.",
  "Why do developers love weekends? Fewer bugs.",
  "Why did the file go missing? Path not found.",
  "Why was the CPU sweating? Too many processes.",
  "Why did the compiler yell? Syntax error!",
  "Why was the app lonely? No users.",
  "Why do programmers hate surprises? Unexpected behavior.",
  "Why was the network slow? Too many packets.",
  "Why did the coder smile? Code finally worked.",

  "Why was the API polite? Good manners.",
  "Why was the database tired? Too many queries.",
  "Why was the screen bright? Full of ideas.",
  "Why did the code blush? It got reviewed.",
  "Why did the app fail? Missing dependencies.",
  "Why do programmers like music? Good loops.",
  "Why was the file confident? Proper permissions.",
  "Why did the program relax? No runtime errors.",
  "Why was the laptop loyal? Always connected.",
  "Why did the script stop? End of line.",

  "Why was the bug relaxed? No debugger.",
  "Why was the system happy? All services running.",
  "Why did the coder panic? Production issue.",
  "Why was the code neat? Proper formatting.",
  "Why did the software smile? Successful build.",
  "Why was the app famous? Went viral.",
  "Why did the function laugh? Good callback.",
  "Why was the server calm? Stable load.",
  "Why was the program proud? Passed all tests.",
  "Why did the coder relax? Deployment done.",

  "Why was the laptop confident? Full battery.",
  "Why was the code clean? No warnings.",
  "Why did the app cheer? Update complete.",
  "Why was the database calm? Indexed properly.",
  "Why was the script fast? Optimized.",
  "Why did the system laugh? Funny logs.",
  "Why was the app quiet? Silent mode.",
  "Why did the code shine? Well commented.",
  "Why was the program ready? All set.",
  "Why did the developer smile? Bug fixed.",

  "Why was the code happy? No errors.",
  "Why was the system strong? Good security.",
  "Why did the program rest? Idle state.",
  "Why was the laptop cool? Good fan.",
  "Why did the coder grin? Successful demo.",
  "Why was the app smooth? No lag.",
  "Why did the code win? Best logic.",
  "Why was the server proud? 100% uptime.",
  "Why did the developer laugh? Code joke.",
  "Why was the program perfect? Almost.",

  "Why did the code sleep? Low power mode.",
  "Why was the system neat? Organized files.",
  "Why was the app bright? Fresh UI.",
  "Why did the program finish? Task complete.",
  "Why was the coder happy? Coffee arrived.",
  "Why was the laptop fast? SSD inside.",
  "Why did the code relax? No deadlines.",
  "Why was the app smart? AI powered.",
  "Why did the system cheer? Update success.",
  "Why was the developer proud? Project done." 
        ];

        function generateJoke() {
            const randomIndex = Math.floor(Math.random() * jokes.length);
            document.getElementById("joke").innerText = jokes[randomIndex];
        }


